export enum BROWSER_EVENTS {
  PAGES_FETCH = "PAGES_FETCH",
  PAGES_FETCH_SUCCESS = "PAGES_FETCH_SUCCESS",
  PAGES_REFRESH = "PAGES_REFRESH",
  PAGES_REFRESH_SUCCESS = "PAGES_REFRESH_SUCCESS",
  PAGES_EDIT = "PAGES_EDIT",
  PAGES_EDIT_SUCCESS = "PAGES_EDIT_SUCCESS",
}
