export enum BROWSER_EVENTS {
  PAGES_FETCH = "PAGES_FETCH",
  PAGES_FETCH_SUCCESS = "PAGES_FETCH_SUCCESS",
  PAGES_REFRESH = "PAGES_REFRESH",
  PAGES_REFRESH_SUCCESS = "PAGES_REFRESH_SUCCESS",
  PAGES_EDIT = "PAGES_EDIT",
  PAGES_EDIT_SUCCESS = "PAGES_EDIT_SUCCESS",
  PAGES_UPDATE = "PAGES_UPDATE",
  PAGES_UPDATE_SUCCESS = "PAGES_UPDATE_SUCCESS",
  PAGES_UPDATE_FAIL = "PAGES_UPDATE_FAIL",
  PAGE_UPLOAD = "PAGE_UPLOAD",
  PAGE_UPLOAD_SUCCESS = "PAGE_UPLOAD_SUCCESS",
  PAGE_UPLOAD_FAIL = "PAGE_UPLOAD_FAIL",
}
