import { BROWSER_EVENTS } from '../../events';
import { createAction } from "@reduxjs/toolkit";
import { DownloadStatus } from '../../models/store';
import { Page } from '../../models';

export const ACTIONS = {
  [BROWSER_EVENTS.CLIENT_FILE_UPLOAD]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_UPLOAD),
  [BROWSER_EVENTS.CLIENT_FILE_UPLOAD_SUCCESS]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_UPLOAD_SUCCESS),
  [BROWSER_EVENTS.CLIENT_FILE_UPLOAD_FAIL]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_UPLOAD_FAIL),
  [BROWSER_EVENTS.CLIENT_FILE_UPLOAD_ALL]: createAction<string[], BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_UPLOAD_ALL),
  [BROWSER_EVENTS.CLIENT_FILE_UPLOAD_ALL_SUCCESS]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_UPLOAD_ALL_SUCCESS),
  [BROWSER_EVENTS.CLIENT_FILE_UPLOAD_ALL_FAIL]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_UPLOAD_ALL_FAIL),
  [BROWSER_EVENTS.CLIENT_FILE_REMOVE]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_REMOVE),
  [BROWSER_EVENTS.CLIENT_FILE_REMOVE_SUCCESS]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_REMOVE_SUCCESS),
  [BROWSER_EVENTS.CLIENT_FILE_REMOVE_FAIL]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_FILE_REMOVE_FAIL),
  [BROWSER_EVENTS.APP_DOWNLOAD]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.APP_DOWNLOAD),
  [BROWSER_EVENTS.APP_DOWNLOAD_STATUS]: createAction<DownloadStatus, BROWSER_EVENTS>(BROWSER_EVENTS.APP_DOWNLOAD_STATUS),
  [BROWSER_EVENTS.APP_DOWNLOAD_PROGRESS]: createAction<number, BROWSER_EVENTS>(BROWSER_EVENTS.APP_DOWNLOAD_PROGRESS),
  [BROWSER_EVENTS.APP_DOWNLOAD_SUCCESS]: createAction<void, BROWSER_EVENTS>(BROWSER_EVENTS.APP_DOWNLOAD_SUCCESS),
  [BROWSER_EVENTS.APP_DOWNLOAD_FAIL]: createAction<void, BROWSER_EVENTS>(BROWSER_EVENTS.APP_DOWNLOAD_FAIL),
  [BROWSER_EVENTS.CLIENT_CATALOG]: createAction<void, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_CATALOG),
  [BROWSER_EVENTS.CLIENT_CATALOG_SUCCESS]: createAction<Page[], BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_CATALOG_SUCCESS),
  [BROWSER_EVENTS.CLIENT_CATALOG_FAIL]: createAction<string, BROWSER_EVENTS>(BROWSER_EVENTS.CLIENT_CATALOG_FAIL),
}
